# This workflow will build wglinfo on Windows
name: Build (Windows/MSVC)

on:
  workflow_call:

jobs:
  build-windows-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64, x86, amd64_arm64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: '${{ matrix.arch }}'

    - name: Configure wglinfo
      run: |
        mkdir "build"
        cmake -G Ninja -D BUILD_TREAT_WARNINGS_AS_ERRORS=ON -S . -B "./build" -D CMAKE_INSTALL_PREFIX="install"

    - name: Build wglinfo
      run: |
        cmake --build "./build" --config Release

    - name: Install wglinfo
      run: |
        cmake --install "./build" --config Release

    - name: Run wglinfo
      if: matrix.arch != 'amd64_arm64'
      run: |
        install/wglinfo.exe
        install/wglinfo.exe > install/wglinfo.log

    - name: Upload artifacts
      if: matrix.arch != 'amd64_arm64'
      uses: actions/upload-artifact@v4
      with:
        name: wglinfo-windows-${{ matrix.arch }}-msvc
        path: install
        if-no-files-found: error

    - name: Upload artifacts
      if: matrix.arch == 'amd64_arm64'
      uses: actions/upload-artifact@v4
      with:
        name: wglinfo-windows-arm64-msvc
        path: install
        if-no-files-found: error
