# This workflow will build wglinfo on Linux
name: Build (Ubuntu)

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        path: wglinfo.git
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ cmake ninja-build \
          libgl-dev libegl-dev \
          libwayland-dev wayland-protocols libxkbcommon-dev \
          xvfb xwayland-run weston
    - name: Configure wglinfo
      env:
        WGLINFO_CONFIG: |
          set(USE_WAYLAND ON CACHE BOOL "")
          set(BUILD_TREAT_WARNINGS_AS_ERRORS ON CACHE BOOL "")
          set(CMAKE_BUILD_TYPE     Release)
          set(CMAKE_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}/wglinfo-install" CACHE PATH "")
      run: |
        echo "${WGLINFO_CONFIG}" | tee ./wglinfo-make.cmake
        cmake -S ./wglinfo.git -B ./wglinfo-make -G Ninja --toolchain "$PWD/wglinfo-make.cmake"
    - name: Build wglinfo
      run: |
        cmake --build ./wglinfo-make
    - name: Install wglinfo
      run: |
        cmake --install ./wglinfo-make --prefix ./wglinfo-install
    - name: Run wglinfo in X11
      run: |
        xvfb-run -a ./wglinfo-install/wglinfo | tee ./wglinfo-install/wglinfo-x11.log
    - name: Run wglinfo in Wayland
      run: |
        wlheadless-run -c weston -- ./wglinfo-install/wglinfo --platform EGL-wayland | tee ./wglinfo-install/wglinfo-wayland.log
    - name: Run wglinfo in X11 / EGL from Chromium
      env:
        EGL_BROWSER_LIBS: /usr/local/share/chromium/chrome-linux
        # these are located here when installed from `apt-get install chromium`
        #EGL_BROWSER_LIBS: /snap/chromium/current/usr/lib/chromium-browser
      run: |
        #ls -la ${EGL_BROWSER_LIBS}
        ldd ${EGL_BROWSER_LIBS}/libEGL.so
        export LD_PRELOAD=${EGL_BROWSER_LIBS}/libEGL.so:${EGL_BROWSER_LIBS}/libGLESv2.so
        xvfb-run -a ./wglinfo-install/wglinfo --platform EGL | tee ./wglinfo-install/wglinfo-x11-chromium.log
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wglinfo-linux-x86_64
        path: wglinfo-install
        if-no-files-found: error
