# This workflow will build wglinfo
name: Build (All)

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    uses: ./.github/workflows/build_wglinfo_ubuntu.yml
  macos:
    uses: ./.github/workflows/build_wglinfo_macos.yml
  windows:
    uses: ./.github/workflows/build_wglinfo_windows.yml
  wasm:
    uses: ./.github/workflows/build_wglinfo_wasm.yml
