# This workflow will build wglinfo on Windows
name: Build (Windows/MSVC)

on:
  workflow_call:

jobs:
  build-windows-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64, x86, arm64, arm32]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        path: wglinfo.git
        fetch-depth: 1
    - name: Configure environment
      id: cfg
      shell: bash
      run: |
        if [ "${{ matrix.arch }}" == "arm64" ]; then
          echo "arch=amd64_arm64" >> $GITHUB_OUTPUT
        elif [ "${{ matrix.arch }}" == "arm32" ]; then
          echo "arch=amd64_arm" >> $GITHUB_OUTPUT
        else
          echo "arch=${{ matrix.arch }}" >> $GITHUB_OUTPUT
        fi
    - name: Install Windows 11 SDK (ARM32)
      if: matrix.arch == 'arm32'
      run: |
        # workaround 'kernel32.lib' missing errors - use older SDK
        # Windows 11 SDK (10.0.22621.2428)
        # https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/index-legacy
        Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=2250105 -OutFile sdksetup.exe -UseBasicParsing
        Unblock-File sdksetup.exe
        Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/ceip off"
    - name: Setup MSVC (ARM32)
      if: matrix.arch == 'arm32'
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: '${{ steps.cfg.outputs.arch }}'
        sdk:  '10.0.22621.0'
    - name: Setup MSVC
      if: matrix.arch != 'arm32'
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: '${{ steps.cfg.outputs.arch }}'
    - name: Configure wglinfo
      shell: cmd
      run: |
        cmake -G Ninja -S ./wglinfo.git -B ./wglinfo-make ^
          -D CMAKE_BUILD_TYPE=Release ^
          -D CMAKE_INSTALL_PREFIX="%CD%/wglinfo-install" ^
          -D BUILD_TREAT_WARNINGS_AS_ERRORS=ON
    - name: Build wglinfo
      run: |
        cmake --build ./wglinfo-make
    - name: Install wglinfo
      run: |
        cmake --install ./wglinfo-make --prefix ./wglinfo-install
    - name: Run wglinfo
      if: ${{ (matrix.arch != 'arm64') && (matrix.arch != 'arm32') }}
      run: |
        ./wglinfo-install/wglinfo.exe
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wglinfo-windows-${{ matrix.arch }}-msvc
        path: wglinfo-install
        if-no-files-found: error
