# This workflow will build wglinfo on macOS
name: Build (macOS/Clang)

on:
  workflow_call:

jobs:
  build-macos-arm64:
    runs-on: macos-15
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        path: wglinfo.git
        fetch-depth: 1
    - name: Configure wglinfo
      env:
        WGLINFO_CONFIG: |
          set(BUILD_TREAT_WARNINGS_AS_ERRORS ON CACHE BOOL "")
          set(CMAKE_BUILD_TYPE     Release)
          set(CMAKE_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}/wglinfo-install" CACHE PATH "")
      run: |
        echo "${WGLINFO_CONFIG}" | tee ./wglinfo-make.cmake
        cmake -S ./wglinfo.git -B ./wglinfo-make -G Ninja --toolchain "$PWD/wglinfo-make.cmake"
    - name: Build wglinfo
      run: |
        cmake --build ./wglinfo-make
    - name: Install wglinfo
      run: |
        cmake --install ./wglinfo-make --prefix ./wglinfo-install
    - name: Run wglinfo
      run: |
        ./wglinfo-install/wglinfo
        ./wglinfo-install/wglinfo 2>&1 > ./wglinfo-install/wglinfo.log
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wglinfo-macos-arm64
        path: wglinfo-install
        if-no-files-found: error

  build-macos-intel:
    runs-on: macos-15-intel
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        path: wglinfo.git
        fetch-depth: 1
    - name: Configure wglinfo
      env:
        WGLINFO_CONFIG: |
          set(BUILD_TREAT_WARNINGS_AS_ERRORS ON CACHE BOOL "")
          set(CMAKE_BUILD_TYPE     Release)
          set(CMAKE_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}/wglinfo-install" CACHE PATH "")
      run: |
        echo "${WGLINFO_CONFIG}" | tee ./wglinfo-make.cmake
        cmake -S ./wglinfo.git -B ./wglinfo-make -G Ninja --toolchain "$PWD/wglinfo-make.cmake"
    - name: Build wglinfo
      run: |
        cmake --build ./wglinfo-make
    - name: Install wglinfo
      run: |
        cmake --install ./wglinfo-make --prefix ./wglinfo-install
    - name: Run wglinfo
      run: |
        ./wglinfo-install/wglinfo
        ./wglinfo-install/wglinfo 2>&1 > ./wglinfo-install/wglinfo.log
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wglinfo-macos-x86_64
        path: wglinfo-install
        if-no-files-found: error
